name: Compilar LaTeX
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout c√≥digo
        uses: actions/checkout@v4 
        
      - name: Compilar PDF
        uses: xu-cheng/latex-action@v3 
        with:
          root_file: main.tex

      - name: Subir PDF como resultado
        uses: actions/upload-artifact@v4 
        with:
          name: Informe-PDF-Generado
          path: main.pdf
