name: Compilar LaTeX
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout c√≥digo
        uses: actions/checkout@v3
      - name: Compilar PDF
        uses: xu-cheng/latex-action@v2
        with:
          root_file: main.tex
      - name: Subir PDF como resultado
        uses: actions/upload-artifact@v3
        with:
          name: Informe-PDF
          path: informe_0_analoga_II.pdf
