name: Compilar y Guardar PDF

on: [push]

permissions:
  contents: write

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Compilar PDF
        uses: xu-cheng/latex-action@v3
        with:
          root_file: main.tex

      - name: Subir PDF al repositorio
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add main.pdf
          git commit -m "Actualización automática del PDF [skip ci]" || echo "No hay cambios en el PDF"
          git push
